### ISSUE TITLE
Dynamic books one frontpage

### ISSUE THREAD

**Issue by Tyratox** [hexcodech/booki-frontend#1]
What books should be showcased?

**Comment by chdabre** [comment]
I think for now just the latest offers. In the future we could switch to a "books with most new offers" model.

**Comment by Tyratox** [comment]
Okey

- How many? Infinite scroll?
- Hover effects?
- Only covers or titles as well?
- I assume a click redirects to the book page?

**Comment by chdabre** [comment]
- Just the single line for now. 
- Maybe a light hover dropshadow effect.
- Tooltip/overlay of title in the future? maybe even a different card design altogether that shows offers.
- click redirects to book page

**Comment by Tyratox** [comment]
Hmm a single line means different things for different devices. Let's just say 4, 6 or something?

**Comment by chdabre** [comment]
Make it six, so it divides to 2x3 and 3x2
