### ISSUE TITLE
Facebook oauth login crashes the server

### ISSUE THREAD

**Issue by Tyratox** [hexcodech/booki-frontend#15]

**Comment by Tyratox** [comment]
Okey its only facebook, google isn't working either but it doesn't crash the server.

**Comment by Tyratox** [comment]
Google is working again, can someone test facebook? @ItsEcholot @davethehacker @chdabre ?

**Comment by Tyratox** [comment]
Still crashing..

**Comment by davethehacker** [comment]
Problem with my google pic
![image](https://user-images.githubusercontent.com/6324096/28138149-08ff3b44-6750-11e7-866b-de0d7c4680a5.png)

**Comment by Tyratox** [comment]
Yeah i noticed this too.. Somehow empty files (in the db) are being created
