### ISSUE TITLE
add logout button

### ISSUE THREAD

**Issue by davethehacker** [hexcodech/booki-frontend#16]
hover-dropdown on username

**Comment by Tyratox** [comment]
Sure on hover? Not click?

**Comment by Tyratox** [comment]
Mobile..?

Also
https://ux.stackexchange.com/questions/94838/should-nav-items-be-hover-or-click-to-activate-dropdown

https://ux.stackexchange.com/questions/62093/hover-or-click-on-dropdown-menu

https://ux.stackexchange.com/questions/13553/better-to-use-hover-vs-click-to-display-dropdown-menus-on-main-navigation-of-we

**Comment by Tyratox** [comment]
Okey for mobile we have the off canvas push menu

**Comment by chdabre** [comment]
As described, this menu does not exist on mobile as the options are stashed away in the slideover menu.

**Comment by Tyratox** [comment]
Not convinced yet, there are more and more touch screen computers..

Another article
http://uxmovement.com/navigation/why-hover-menus-do-users-more-harm-than-good/

Also why should we do it on `hover`?

**Comment by chdabre** [comment]
OK click is fine by me

**Comment by Tyratox** [comment]
@davethehacker @ItsEcholot ?

**Comment by ItsEcholot** [comment]
I would vote for on click
