### ISSUE TITLE
Add dropdown menu for user controls

### ISSUE THREAD

**Issue by chdabre** [hexcodech/booki-frontend#17]
See Image. On Mobile, these options appear similar, with the enlarged picture, as links instead of buttons, in the slide menu.

The slide menu items from top to bottom would then be:
- Profile Pic (centered)
- Name (centered)
- KAUFEN
- VERKAUFEN
- MEIN PROFIL
- LOGOUT

<img width="1039" alt="bildschirmfoto 2017-07-12 um 20 14 12" src="https://user-images.githubusercontent.com/7313617/28133388-2027d110-6740-11e7-8cd1-7009d130df02.png">

**Comment by Tyratox** [comment]
Uploaded wrong image?

**Comment by chdabre** [comment]
yes.

<img width="427" alt="bildschirmfoto 2017-07-16 um 12 41 23" src="https://user-images.githubusercontent.com/7313617/28246848-1a618a5a-6a24-11e7-9422-3246cc02fb5a.png">
