### ISSUE TITLE
Change User profile to be more in-line with the design.

### ISSUE THREAD

**Issue by chdabre** [hexcodech/booki-frontend#19]
Also integrates with new features introduced in Issue #18 

![01](https://user-images.githubusercontent.com/7313617/28135111-6e307056-6745-11e7-9057-e6d2873d0ca1.png)
![02](https://user-images.githubusercontent.com/7313617/28135112-6e5901c4-6745-11e7-84d5-31670617c921.png)

**Comment by Tyratox** [comment]
(only the design, the buttons don't work yet) We'll just have to dispatch the correct action defined in the core.
