### ISSUE TITLE
Add more book condition options

### ISSUE THREAD

**Issue by chdabre** [hexcodech/booki-frontend#22]
currently only good/bad

**Comment by Tyratox** [comment]
Well ehm what other options? These are just entries in the db and locale mappings on the frontend.

**Comment by chdabre** [comment]
I think theres a scale from bad to good in the onenote

Von meinem iPhone gesendet

**Comment by ItsEcholot** [comment]
Here's a quick screengrab of the mentioned scale:

![image](https://user-images.githubusercontent.com/2771251/28667233-f2fd5eee-72ca-11e7-83b4-815f9362d5af.png)
